function advm_param_struct = default_advm_param_struct

v = [];

advm_param_struct = struct( ...
    'Frequency',            v           ,...
    'EffectiveDiameter',    v           ,...
    'BeamOrientation',      'Horizontal',...
    'SlantAngle',           v           ,...
    'Nbeams',               v           ,...
    'BlankDistance',        v           ,...
    'CellSize',             v           ,...
    'NumberOfCells',        v           ,...
    'BeamNumber',           'Avg'       ,...
    'MovingAverageSpan',    1           ,...
    'BSValues',             'SNR'       ,...
    'IntenScale',           v           ,...
    'RMin',                 -Inf        ,...
    'RMax',                  Inf        ,...
    'MinCells',             2           ,...
    'MinVbeam',             -Inf        ,...
    'NearField',            false       ,...
    'RemoveMinWCB',         false        ...
    );